#ifndef   CTL_CODE
#pragma message("\n \n-----------EXE模式 Include winioctl.h ")
#include<winioctl.h> //CTL_CODE ntddk.h wdm.h
#else 
#pragma message("-\n \n---------SYS模式NO Include winioctl.h ")
#endif

//#define TEST_1 CTL_CODE(FILE_DEVICE_UNKNOWN,0x800,METHOD_IN_DIRECT,FILE_ANY_ACCESS)
//#define SSDT_NtOpenProcess_Hook_Code CTL_CODE(FILE_DEVICE_UNKNOWN,0x801,METHOD_IN_DIRECT,FILE_ANY_ACCESS)
//#define Inline_NtOpenProcess_Hook_Code CTL_CODE(FILE_DEVICE_UNKNOWN,0x802,METHOD_IN_DIRECT,FILE_ANY_ACCESS)
//#define TP_DDK_Enable_Code CTL_CODE(FILE_DEVICE_UNKNOWN,0x803,METHOD_IN_DIRECT,FILE_ANY_ACCESS)

#define FILE_DEVICE_COMM_DRIVER 0x00008811

#define IOCTL_COMM_DIRECT_IN_IO    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_IN_DIRECT,  FILE_ANY_ACCESS) 
#define IOCTL_COMM_DIRECT_OUT_IO   CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_OUT_DIRECT, FILE_ANY_ACCESS) 
#define IOCTL_COMM_BUFFERED_IO     CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED,   FILE_ANY_ACCESS)
#define IOCTL_COMM_NEITHER_IO      CTL_CODE(FILE_DEVICE_UNKNOWN, 0x803, METHOD_NEITHER,    FILE_ANY_ACCESS)
#define IOCTL_TP_DDK_ENABLE		CTL_CODE(FILE_DEVICE_UNKNOWN, 0x804, METHOD_IN_DIRECT,   FILE_ANY_ACCESS)
